kind: pipeline
type: docker
name: Testing Python CI/CD

steps:
  - name: Install dependencies and run script
    image: python:3.10
    environment:
      MY_PASS:
        from_secret: MY_PASS
    commands:
      - pip install Flask==2.1.0 requests==2.27.1 pytest==7.2.0
      - python bat.py

trigger:
  branch:
    include:
      - main
