kind: pipeline
type: docker
name: Testing Python CI/CD

steps:
  - name: Install and deploy
    image: python:3.10
    environment:
      MY_PASS:
        from_secret: MY_PASS
    commands:
      - pip install -r requirements.txt
      - python bat.py

trigger:
  branch:
    exclude:
      - main
      - master
