kind: pipeline
type: docker
name: Testing Python CI/CD

steps:
  - name: Install and deploy
    image: python:3.10
    environment:
      MY_PASS:
        from_secret: MY_PASS  # Replace with your actual secret name if needed
    commands:
      - ls -alh  # List files for debugging
      - pip install -r requirements.txt  # Install dependencies from requirements.txt
      - python bat.py  # Run your Python script (bat.py)

trigger:
  branch:
    include:
      - main  # Trigger pipeline on the 'main' branch
